FROM python:3.9


# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app  


# Copy project files
COPY wait-for-it-master/wait-for-it.sh /usr/local/bin/wait-for-it.sh
COPY src/requirements.txt ./src-requirements.txt
COPY selenium_scraper_container/requirements.txt ./scraper-requirements.txt
COPY rbmq ./rbmq/ 
COPY shared_paths.py ./
COPY selenium_scraper_container/ ./selenium_scraper_container/

copy src/ ./src/

#make wait-for-it script executable
RUN chmod +x /usr/local/bin/wait-for-it.sh


#install python dependencies from both requirement files with error handling
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r src-requirements.txt && \
    pip install --no-cache-dir -r scraper-requirements.txt
EXPOSE 7777


CMD ["python", "app/rbmq/search_request_worker.py"]